DOCUMENTS = [
    {
        "id": "QS-001",
        "title": "QS World University Rankings Overview",
        "content": "The QS World University Rankings portfolio, inaugurated in 2004, has grown to become the world's most popular source of comparative data about university performance. The main rankings are based on six metrics: Academic Reputation (40%), Employer Reputation (10%), Faculty/Student Ratio (20%), Citations per Faculty (20%), International Faculty Ratio (5%), and International Student Ratio (5%).",
        "category": "Ranking Frameworks",
        "keywords": ["QS", "metrics", "weights", "overview", "academic reputation"],
    },
    {
        "id": "THE-001",
        "title": "Times Higher Education (THE) Methodology",
        "content": "The Times Higher Education World University Rankings judge research-intensive universities across all their core missions: teaching, research, knowledge transfer and international outlook. It uses 13 carefully calibrated performance indicators to provide the most comprehensive and balanced comparisons, trusted by students, academics, university leaders, industry and governments.",
        "category": "Ranking Frameworks",
        "keywords": ["THE", "Times", "methodology", "indicators", "research"],
    },
    {
        "id": "APP-001",
        "title": "Dashboard Features",
        "content": "The Dashboard serves as the central hub for your institution's assessment. It displays the active HEI profile, selected ranking framework (QS or THE), and a progress tracker. Users can input data for key metrics like Academic Reputation, Citations per Faculty, and Sustainability. The dashboard also facilitates evidence file uploads for each category to validate the scores.",
        "category": "App Features",
        "keywords": ["dashboard", "features", "data entry", "upload", "evidence"],
    },
    {
        "id": "APP-002",
        "title": "Analytics Page",
        "content": "The Analytics page provides deep insights into your institution's performance. It features real-time scoring visualizations including a breakdown of Overall Readiness, Research & Discovery, Employability, and Global Engagement scores. It compares your metrics against NCR averages and target benchmarks using bar charts. Additionally, it offers AI-Powered Strategic Recommendations to suggest actionable steps for improvement.",
        "category": "App Features",
        "keywords": [
            "analytics",
            "charts",
            "comparison",
            "benchmarks",
            "AI recommendations",
        ],
    },
    {
        "id": "APP-003",
        "title": "Institutions Management",
        "content": "The Institutions page is for managing HEI profiles. Administrators can view a list of all registered institutions, search by name or address, check assessment status (Active vs. Pending), and perform actions like editing details or deleting institution records. It also provides summary statistics on total and active institutions.",
        "category": "App Features",
        "keywords": ["institutions", "management", "admin", "search", "delete"],
    },
    {
        "id": "APP-004",
        "title": "Reports Generation",
        "content": "The Reports page allows users to generate and download performance reports. It lists all generated reports with their status (Completed, In Progress), overall scores, and breakdown by dimension. Users can download individual reports as CSV files or download a bulk CSV containing data for all institutions.",
        "category": "App Features",
        "keywords": ["reports", "download", "csv", "export", "status"],
    },
    {
        "id": "GDE-001",
        "title": "How to Upload Evidence Files",
        "content": "To upload evidence files: 1. Navigate to the Dashboard. 2. Locate the specific metric section (e.g., Research and Discovery). 3. Drag and drop files into the upload area or click to browse. 4. Supported file types are PDF, PNG, and JPG. 5. Once uploaded, files will appear in the list and can be clicked to view. 6. Click 'Save Progress' at the bottom of the page to persist the uploads.",
        "category": "Guides",
        "keywords": ["upload", "files", "evidence", "guide", "how to"],
    },
    {
        "id": "GDE-002",
        "title": "Calculating Citations per Faculty",
        "content": "Citations per Faculty is a measure of research impact. It is calculated by dividing the total number of citations received by all papers produced by an institution over a five-year period by the number of faculty members at that institution. In this app, simply enter the calculated ratio in the 'Citations per Faculty' input field in the Dashboard.",
        "category": "Guides",
        "keywords": ["citations", "faculty", "calculation", "research", "formula"],
    },
    {
        "id": "FAQ-001",
        "title": "How do I change my ranking framework?",
        "content": "You can change your ranking framework in the Settings page under 'Assessment Framework'. Note that switching between QS and THE will alter the required data fields and scoring logic. Existing data may not be fully compatible with the new framework, so proceed with caution.",
        "category": "FAQ",
        "keywords": ["change", "framework", "QS", "THE", "settings"],
    },
    {
        "id": "FAQ-002",
        "title": "What happens if I delete an institution?",
        "content": "Deleting an institution is a destructive action. It will remove the institution's profile, all associated assessment scores, uploaded evidence links, and generated reports from the database. This action cannot be undone. You will be asked to confirm before the deletion is finalized.",
        "category": "FAQ",
        "keywords": ["delete", "remove", "institution", "warning", "data loss"],
    },
]